language: go

go:
  - 1.8

before_install:
  - travis_retry go get -u golang.org/x/lint/golint

script:
  - go test -v ./... &&
    go vet ./...&&
    golint ./... &&
    scripts/check_gofmt.sh

notifications:
  email:
    on_success: never
