language: go

go:
  - 1.8

before_install:
  - go get -u github.com/golang/lint/golint

script:
  - go test -v ./... &&
    go vet ./...&&
    golint &&
    scripts/check_gofmt.sh

notifications:
  email:
    on_success: never
