name: hncheck CI

env:
  GO_VERSION: 1.19

on:
  pull_request:
  push:
  schedule:
    # once a day at 08:00
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "go env GOPATH=$(go env GOPATH)"
          echo "pwd=$(pwd)"
          echo "HOME=${HOME}"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"

      - name: "Go: Install"
        run: go install

      - name: "Go: Test"
        run: go test -v ./...

      - name: "Check: Gofmt"
        run: scripts/check_gofmt.sh
